### ISSUE TITLE
Random _transferSize values

### ISSUE THREAD

**Issue by sjfricke** [cyrus-and/chrome-har-capturer#41]
I have a demo site running HTTP\2.0 [here](https://http2optimization.com/W_2_2_a/) and its just downloads 50 Javascript objects of all the same size.

When I open chrome manually and grab the HAR I always will get a `_transferSize` of 20250 for every one

When I use the chrome-har-capturer
```
var chc = require('chrome-har-capturer');
var c = chc.load(['https://http2optimization.com/W_2_2_a/']);
c.on('end', function (har) {
   console.log ( har );
});
```
Not only do I get `_transferSize` of 20027 but sometimes I will get random lower values ranging from 0 - 20000 for like 1 or 2 of the 50 files

I also notice the files that get a random less `_transferSize` will have way quicker timing values as well

Also: I am running chrome headless with the `--incognito` flag as well so there is no way it should be caching any of it neither

**Comment by cyrus-and** [comment]
I'm unable to reproduce what you experience, I'm testing with:

    chrome-har-capturer 'https://http2optimization.com/W_2_2_a/' \
        | grep _transferSize | sort | uniq -c

and I repeatedly get:

```
DONE https://http2optimization.com/W_2_2_a/
     50                     "_transferSize": 20027,
      1                     "_transferSize": 268,
```

Chrome version `57.0.2987.110`.

---

For what concerns the 20027 vs 20250, I really don't know, I simply sum up all the chunks that Chrome receives and reports via the `Network.dataReceived` event. I guess the difference is due to headers in the HTTP/2.0 case. As you can [see][1], the whole size computation is quite tricky; Chrome just doesn't provide the values clearly.

[1]: https://github.com/cyrus-and/chrome-har-capturer/blob/600dec3c62e4c8d65013fc12b99bd1c43e7059fe/lib/har.js#L96-L129

**Comment by sjfricke** [comment]
I am running Chromium `56.0.2924.76` and running it I still get an off value every 4th or so time... I am gonna try both updating Chromium and also try running it with a debugger in the `fromPage` call and others and see if I can pin point something that is off that might be throwing the calculation off... I also am quite shocked that their internal HAR loader doesn't have an explanation how it gets the `_transferSize`

Will update my findings in next day or two

**Comment by sjfricke** [comment]
So I ran it again on `Ubuntu 16.04.2 LTS` 

The desktop running chrome -v 57 works 100%

The Raspberry Pi running -v 56 is the one having the inconsistency, so could be something where it returns the data for the request in a different way. I do notice that all the ones that are off are one of the first 3 or so javascript objects being loaded

**Comment by cyrus-and** [comment]
So can we agree that this is a problem with that specific version of Chrome? Have you tried anything else?

**Comment by benschwarz** [comment]
I'm unsure if this is related, but I recently upgraded to `0.9.3` — I'm seeing a bunch of `_transferSize` entries returned as `-1`

**Comment by cyrus-and** [comment]
@benschwarz what was the prior version? Are you able to reliably obtain this behavior? If that's the case, post it here so I can attempt to reproduce your issue.

**Comment by sjfricke** [comment]
I reran it a 100 times on each device with 
`chrome-har-capturer 'https://http2optimization.com/W_2_20_a/' | grep _transferSize | sort | uniq -c`
 
And the Pi running Chrome 56 had random value quite a bit, but my desktop also had a 0 transfer value twice in the run

I did try testing it with different sizes and I find it really only happens when there are exceedingly higher number of entries to grab (in this case 150) and running
`chrome-har-capturer 'https://http2optimization.com/W_2_2_a/' | grep _transferSize | sort | uniq -c`
I never get any random values with only 3 entries

But it not the version of chrome

Also both tests were ran on `0.9.3`

**Comment by sjfricke** [comment]
@cyrus-and 
Looking more into the [debugging API](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#event-dataReceived) I noticed you are using the `encodedDataLength` for the `_transferSize` which means it will be less if it is compressed and sent over gzip.... what I don't get is why there is an inconsistency when I run it still

**Comment by cyrus-and** [comment]
@sjfricke 

> Looking more into the debugging API I noticed you are using the encodedDataLength for the _transferSize which means it will be less if it is compressed and sent over gzip....

Which should be OK since `_transferSize` is the on-the-wire application data bytes.

> why not just set the objects[id].encodedResponseLength during the Network.loadingFinished event instead of trying to gather it part by part in chunks?

Now that's a good question... look, I can't remember and I cannot even search through the commit history since I sum up the data chunks since the first revision. I do remember though that it was a workaround, so probably either `Network.loadingFinished.encodedDataLength` wasn't there at the time or it returned an invalid value.

In fact, it seems that it has been introduced in 2014 while the first commit dates back to 2012...

Anyway I'm OK with using `Network.loadingFinished.encodedDataLength` as is for the `_transferSize`.

> but the values is given as the "size" and not the "content" being sent across, which I am not 100% which is more accurate of it sending all the data across

I do not understand the point here, care to elaborate a bit?

**Comment by cyrus-and** [comment]
@sjfricke I've just pushed a candidate fix to [this temp branch][1], can you give it a try? Basically I'm using `Network.loadingFinished.encodedDataLength` in place of the sum of `Network.dataReceived.encodedDataLength`.

[1]: https://github.com/cyrus-and/chrome-har-capturer/tree/test-41

**Comment by benschwarz** [comment]
@cyrus-and, sorry for the radio silence 👂📻 !

Using @sjfricke's example script, I ran a few tests using Chrome stable (current: 57.0.2987.133 Mac) both against 0.9.3, and @cyrus-and's `test-41` branch. 

### The test script
Node 7.8.0, `chrome-har-capturer`, `console.table` required

```js
const path = require('path')
const URL = require('url')
require('console.table')

const chc = require('chrome-har-capturer');

const c = chc.load(['https://mobile.twitter.com/benschwarz']);
c.on('end', function (har) {
  // Render the formatted har
  // console.log ( JSON.stringify(har, null, 2) )

  const requests = har.log.entries.map(entry => {
    const url = URL.parse(entry.request.url)
    const basename = path.basename(url.path)

    const { httpVersion, bodySize, headersSize, _transferSize } = entry.response
    const contentSize = entry.response.content.size

    return { basename, httpVersion, headersSize, bodySize, _transferSize, contentSize }
  })

  console.table(requests)

  console.log(`${har.log.entries.length} requests`)
})
```

Firstly, when I ran this against `test-41` I saw a different number of entries in the har file — eg, on file consecutive runs of this script, I saw different numbers of requests. At any rate, I'm unsure if this is Twitter A/B testing, tracking code or otherwise (but thought it important to mention). 

<details>
<summary>Run against `test-41`</summary>

```
basename                                      httpVersion  headersSize  bodySize  _transferSize  contentSize
--------------------------------------------  -----------  -----------  --------  -------------  -----------
benschwarz                                    h2           -1           -1        5588           11695
manifest.0146668f9524363d.js                  h2           -1           -1        0              5597
vendor.54b74c072cb2d26f.js                    h2           -1           -1        0              316260
en.a37317eb80076832.js                        h2           -1           -1        0              104475
main.5ea20cc47406d075.js                      h2           -1           -1        0              352779
0.0929ede1b183bfbf.js                         h2           -1           -1        0              500010
loader.notificationsData.8b5f065f59e07314.js  h2           -1           -1        0              7187

7 requests
```

</details>


<details>
<summary>Run against `0.9.3`</summary>

```
basename                                      httpVersion  headersSize  bodySize  _transferSize  contentSize
--------------------------------------------  -----------  -----------  --------  -------------  -----------
benschwarz                                    h2           -1           -1        2565           11851
manifest.0146668f9524363d.js                  h2           -1           -1        0              5597
vendor.54b74c072cb2d26f.js                    h2           -1           -1        0              316260
en.a37317eb80076832.js                        h2           -1           -1        0              104475
main.5ea20cc47406d075.js                      h2           -1           -1        0              352779
0.0929ede1b183bfbf.js                         h2           -1           -1        0              500010
loader.notificationsData.8b5f065f59e07314.js  h2           -1           -1        0              7187
```

</details>

Consecutive runs against both `0.9.3` and `test-41` observed different `_transferSize` values, neither were able to return `headersSize` or `bodySize` values for `h2` requests.

**Comment by benschwarz** [comment]
Additional (maybe) interest: 

* Version `0.8.1` reported 

```
basename    httpVersion  headersSize  bodySize  _transferSize  contentSize
----------  -----------  -----------  --------  -------------  -----------
W_2_2_a     h2           -1           -1        0              195
object1.js  h2           -1           -1        150696         166666
object2.js  h2           -1           -1        166855         166666
object3.js  h2           -1           -1        166855         166666
```

* Version `0.7.0` reported:

```
basename    httpVersion  headersSize  bodySize  _transferSize  contentSize
----------  -----------  -----------  --------  -------------  -----------
W_2_2_a     h2           336          -336      0              195
object1.js  h2           372          150324    150696         166666
object2.js  h2           372          166483    166855         166666
object3.js  h2           372          166483    166855         166666
```

I've no idea if these header and body size values are correct, but all the same — they're present.

**Comment by benschwarz** [comment]
I'd say that from my tests, the `test-41` changes appear to yield a correct `_transferSize`

**Comment by benschwarz** [comment]
@cyrus-and, I know its a different issue (same train of thought though 🚂 💭)—I did some ["Twitter research"](https://twitter.com/benschwarz/status/849863605138759681) regarding the header and body sizes in HTTP2. 

@paulirish, would it be possible to have Chrome return the header size (post HPACK compression) via chrome remote protocol? I suspect there aren't security concerns, being as the headers are already returned anyway.

**Comment by cyrus-and** [comment]
Thanks @benschwarz for the extensive testing, I really appreciate that.

Just a note: version `0.7.0` is not aware of the fact that headers can be compressed, so that values are simply wrong.

> regarding the header and body sizes in HTTP2.

Trying to (re)compress the headers in the same conditions might work but it's surely a quite fragile approach due to the free choices allowed by the spec, e.g., the [Dynamic Table][1]. *(Disclaimer: I just skimmed through the spec.)*

> I suspect there aren't security concerns, being as the headers are already returned anyway.

I agree, there should be no security implications IMHO.

[1]: http://httpwg.org/specs/rfc7541.html#rfc.section.2.3.2

---

I think I've found a way to find out the compressed header size (and thus the body size). The following is proven empirically as the documentation doesn't help:

1. `Network.loadingFinished.encodedDataLength` is the total on-the-wire data (including the headers);
2. summing up all the `Network.dataReceived.encodedDataLength` yields the on-the-wire data of the body alone;
3. summing up all the `Network.dataReceived.dataLength` yields the decoded body size.

So the difference between 1. and 2. should yield the header size (regardless the compression).

I wrote a script to test this:

```js
const CDP = require('chrome-remote-interface');

const url = process.argv[2] || 'http://example.com';

CDP(async (client) => {
    const {Network, Page} = client;
    const sizes = {};

    Network.requestWillBeSent((params) => {
        const {requestId} = params;
        console.log(`[${requestId}] --- REQUEST WILL BE SENT`);
        sizes[params.requestId] = {
            dataLength: 0,
            encodedDataLength: 0
        };
    });

    Network.dataReceived((params) => {
        const {requestId, dataLength, encodedDataLength} = params;
        console.log(`[${requestId}] --- DATA RECEIVED`);
        console.log(`[${requestId}] dataLength             = ${dataLength}`);
        console.log(`[${requestId}] encodedDataLength      = ${encodedDataLength}`);
        sizes[requestId].dataLength += dataLength;
        sizes[requestId].encodedDataLength += encodedDataLength;
    });

    Network.responseReceived((params) => {
        const {requestId, response} = params;
        const contentLength = response.headers['content-length'] || response.headers['Content-Length'];
        console.log(`[${requestId}] --- RESPONSE RECEIVED`);
        console.log(`[${requestId}] content-length         = ${contentLength}`);
    });

    Network.loadingFinished((params) => {
        const {requestId, encodedDataLength} = params;
        const sum = sizes[params.requestId];
        const headerSize = encodedDataLength - sum.encodedDataLength;
        console.log(`[${requestId}] --- LOADING FINISHED`);
        console.log(`[${requestId}] sum dataLength         = ${sum.dataLength}`);
        console.log(`[${requestId}] sum encodedDataLength  = ${sum.encodedDataLength}`);
        console.log(`[${requestId}] encodedDataLength      = ${encodedDataLength}`);
        console.log(`[${requestId}] header size (?)        = ${headerSize}`);
    });

    Page.loadEventFired(() => {
        client.close();
    });

    try {
        await Network.enable();
        await Network.clearBrowserCache();
        await Page.enable();
        await Page.navigate({url});
    } catch (err) {
        console.error(err);
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});

```

And here's what I obtain:

```
[15186.1] --- REQUEST WILL BE SENT
[15186.1] --- RESPONSE RECEIVED
[15186.1] Content-Length         = 166666
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 0
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16474
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16492
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 16366
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 2898
[15186.1] encodedDataLength      = 16384
[15186.1] --- DATA RECEIVED
[15186.1] dataLength             = 0
[15186.1] encodedDataLength      = 2907
[15186.1] --- LOADING FINISHED
[15186.1] sum dataLength         = 166666
[15186.1] sum encodedDataLength  = 166855
[15186.1] encodedDataLength      = 167080
[15186.1] header size (?)        = 225
```

Using Wireshark (and running Chromium with `export SSLKEYLOGFILE` to decrypt the traffic) I get:

```
Frame 119: 1514 bytes on wire (12112 bits), 1514 bytes captured (12112 bits) on interface 0
Ethernet II, Src: Technico_19:17:16 (e0:b9:e5:19:17:16), Dst: Dell_fe:36:d8 (a4:ba:db:fe:36:d8)
Internet Protocol Version 4, Src: 24.240.32.197, Dst: 192.168.1.117
Transmission Control Protocol, Src Port: 443, Dst Port: 49344, Seq: 19630, Ack: 801, Len: 1448
[12 Reassembled TCP Segments (16413 bytes): #82(1448), #85(1448), #87(1448), #88(1448), #90(1448), #91(1448), #93(1448), #108(1448), #112(1448), #114(1448), #116(1448), #119(485)]
Secure Sockets Layer
HyperText Transfer Protocol 2
    Stream: HEADERS, Stream ID: 1, Length 216
        Length: 216
        Type: HEADERS (1)
        Flags: 0x04
        0... .... .... .... .... .... .... .... = Reserved: 0x0
        .000 0000 0000 0000 0000 0000 0000 0001 = Stream Identifier: 1
        [Pad Length: 0]
        Header Block Fragment: 887691aa6355e580ae102e053fae11db526dfeff6196df3d...
        [Header Length: 400]
        [Header Count: 11]
        Header: :status: 200
        Header: server: nginx/1.10.0 (Ubuntu)
        Header: date: Thu, 06 Apr 2017 15:53:23 GMT
        Header: content-type: application/javascript
        Header: content-length: 166666
        Header: last-modified: Sat, 01 Apr 2017 04:51:18 GMT
        Header: etag: "58df31c6-28b0a"
        Header: strict-transport-security: max-age=63072000; includeSubdomains
        Header: x-frame-options: DENY
        Header: x-content-type-options: nosniff
        Header: accept-ranges: bytes
        Padding: <MISSING>
    Stream: DATA, Stream ID: 1, Length 8192
        Length: 8192
        Type: DATA (0)
        Flags: 0x00
        0... .... .... .... .... .... .... .... = Reserved: 0x0
        .000 0000 0000 0000 0000 0000 0000 0001 = Stream Identifier: 1
        [Pad Length: 0]
        Data: b775753fcc8585c1f96afd85d2d7b478577fa4e2f33b8d22...
        Padding: <MISSING>
```

Note the `Stream: HEADERS, Stream ID: 1, Length 216` instead of 225. Other URLs (Wireshark vs Node.js):
- `https://example.com` (http2) 163 vs 172;
- `http://example.com` (http) vs 364 vs 350.

---

**Update:** it seems that `Network.loadingFinished.encodedDataLength` also takes into account low-level networking traffic too (e.g., it's larger after flushing the sockets via `chrome://net-internals/#sockets` probably due to the TLS handshake) so I don't think it can be wise to use it to compute the header size.

**Comment by benschwarz** [comment]
@cyrus-and, are you able to merge `test-41` and cut a `0.9.4` release?

**Comment by cyrus-and** [comment]
@benschwarz done.
