### ISSUE TITLE
startedDateTime ignores queuing

### ISSUE THREAD

**Issue by KiwiKilian** [cyrus-and/chrome-har-capturer#47]
I just compared HAR files generated by Chrome network tab and the capturer. The capturer seems to return a incorrect startedDateTime, missing the offset by queuing, which can be seen the Chrome network tab and HAR files saved from Chrome. Here are two har files viewed with [har viewer](http://www.softwareishard.com/har/viewer/), the same page was loaded in booth cases.

**HAR saved by Chrome**
![chrome](https://user-images.githubusercontent.com/18724559/27255578-b70b7806-53a0-11e7-8714-bc677d5b8e31.png)

**HAR saved by capturer**
![capturer](https://user-images.githubusercontent.com/18724559/27255577-b70b08ee-53a0-11e7-82ac-fa485a496995.png)

Therefore I think the Network.requestWillBeSent() walltime value from the devtools protocols, which is used for the startedDateTime ([see code](https://github.com/cyrus-and/chrome-har-capturer/blob/master/lib/har.js#L70)), does not actually mean, the request will be sent at that point? I just tried the timestamp value to calculate the startedDateTime, this produces the same problem.

Could startedDateTime be calculated inverse from Network.responseReceived() minus the time it entry.time value and than convert back to walltime?

**Comment by cyrus-and** [comment]
I see your point, and definitely there's something to fix here, in fact I'd like to be able to reproduce this (and possibly other timing-related issues) using a minimal example so to finally fix it and add it as a regression test. If you are aware of a minimal consistent way of reproducing this please post it here.

Anyway, I'm not sure that the missing queuing time (`blocked`) is caused by `startedDateTime`, [see here][1].

I'll dig deeper into this...

[1]: https://github.com/cyrus-and/chrome-har-capturer/blob/ed7c725e75bf1f463ebcc3b35edf816b17460597/lib/har.js#L179-L181

**Comment by cyrus-and** [comment]
Better late than never... the following seems to reproduce this issue.

`server.js`

```js
const fs = require('fs');
const http = require('http');

const image = fs.readFileSync('image.jpg');

const server = http.createServer((req, res) => {
    if (req.url === '/') {
        let out = '';
        for (let i = 0; i < 100; i++) {
            out += `<img src="/${i}.jpg" />\n`;
        }
        res.setHeader('content-type', 'text/html');
        res.end(out);
    } else if (req.url.match(/\.jpg$/)) {
        res.setHeader('content-type', 'image/jpeg');
        res.end(image);
    }
});

server.listen(8080);
```

Then:

```console
$ wget https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg -O image.jpg
$ node server.js &
$ chrome-har-capturer http://localhost:8080 -o chc.har
```
