### ISSUE TITLE
Compatibility of version 0.9.5 with headless chrome

### ISSUE THREAD

**Issue by sa91** [cyrus-and/chrome-har-capturer#48]
I wanted to know whether chrome-har-capturer  version 0.9.5 is compatible with headless chrome , I am using this version in my project. If there is way I can use it with headless chrome, please guide me.

**Comment by cyrus-and** [comment]
Yes it is, but it doesn't seem to support the `--enable-benchmarking` and the `--enable-net-benchmarking` flags, so you'll have to use the `force` option.

Anyway please bear in mind the [note][1] in the README. The problem is usually the other way around, if you can use Chrome in headless mode you can easily just switch to the latest chrome-har-capturer version in your project.

[1]: https://github.com/cyrus-and/chrome-har-capturer#setup
