### ISSUE TITLE
post request not supported

### ISSUE THREAD

**Issue by NandaBalakrishnan** [cyrus-and/chrome-har-capturer#55]
hi,
   1) i want to know whether chrome-har-capture supports http post request/ get request with headers, query params etc.. , if it so how to do that.
2)how to aggregate the multiple har generated for multiple task to single har file.
please reply ASAP

Thanks.

**Comment by cyrus-and** [comment]
1. GET querystrings can be found in `entries[i].request.queryString`, similarly for headers. I'm going to add POST data soon.

2. You can just create a new HAR file and merge all the `pages` and all the `entries`. Since 00ed485cd4b41010606eed8989fd896f861e62dd the `pageref` field is random so there should be no conflicts.

**Comment by cyrus-and** [comment]
> I'm going to add POST data soon.

Done, please give it a try.

**Comment by NandaBalakrishnan** [comment]
hi, 
  I am asking about how to pass the header and query params for GET request to get back har.

**Comment by cyrus-and** [comment]
Headers can be passed with the `-H` option and the query parameters are part of the URL itself; I'm not sure I'm understanding what you're asking here.
